/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-02-15 00:13:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"titlebox\" style=\"background-color:#465e67; height:18%; margin-top:none;\">\r\n");
      out.write("<div id=\"title\" style=\"margin-top:30px; margin-left:50px; float:left;\"><font size=\"6px\" color=\"white\">Online Classroom</font></div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"menu\" style=\"margin-top:50px; margin-right:40px; float:right; \">\r\n");
      out.write("<a href= \"forum\" style=\"text-decoration:none; margin-right:10px;\"><font color=\"white\"; size=\"4px\";>Forums</font></a>\r\n");
      out.write("<a href= \"chat\" style=\"text-decoration:none; margin-right:10px;\"><font color=\"white\"; size =\"4px\">Chat</font></a>\r\n");
      out.write("<a href= \"materials\" style=\"text-decoration:none; margin-right:10px;\"><font color=\"white\"; size =\"4px\">Materials</font></a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"logos\"; style=\"margin-top:20px; margin-left:30px; border: 1px solid #465e67; width:200px; float:left;\">\r\n");
      out.write("<img src=\"https://fbcdn-photos-h-a.akamaihd.net/hphotos-ak-prn1/v/t34/1077951_10201100917159620_1672902962_a.jpg?oh=415fbf9c74f234211abe2dc5a5648a07&oe=52EEBD34&__gda__=1391376688_4c8d6f92084aa352fff6dbbb52aedc0e\" alt=\"UP Department of Computer Science\" style=\"margin-top:10px; margin-left:10px; margin-bottom:10px;\" height=\"176\" width=\"180\"/>\r\n");
      out.write("<img src=\"https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-prn2/v/t34/1616577_10201100916919614_1458609028_n.jpg?oh=d3cf73cafbbd4c58b0f120666de150e9&oe=52EE731A&__gda__=1391380748_4d935486c313ca46ee09dbcf384c5de9\" alt=\"UP Department of Computer Science\" style=\"margin-top:10px; margin-left:10px; margin-bottom:10px;\" height=\"176\" width=\"180\"/>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"textbox\"; style=\"margin-top:20px; margin-right:30px;width:75%; float:right;\">\r\n");
      out.write("<div id=\"text\"; style = \"margin-top:10px; margin-left:10px; margin-right:10px;\">\r\n");
      out.write("\r\n");
      out.write("</br></br><h1><b><font color=#465e67 size=\"7px\"><center>LEARNING RESOURCES<font color=#999999>,</font> COLLABORATION<font color=#999999> &</font> CONFERENCE</center></b></h1>\r\n");
      out.write("\r\n");
      out.write("<P> <font size=\"4px\"><p align=\"justify\">This online classroom, is an exclusive platform for collaboration with your Department of Computer Science fellows. \r\n");
      out.write("Access a plethora of review materials and learning resources.\r\n");
      out.write("Gain feedback from the entire UP DCS network.\r\n");
      out.write("Hold a conference or study session with anyone in the department.\r\n");
      out.write("<i>Share your expertise.</i></font></p>\r\n");
      out.write("</font>\r\n");
      out.write("</div>\r\n");
      out.write("</font>\r\n");
      out.write("</div>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
