/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-03-29 02:15:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class subjectList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Blue Coffee</title>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<link type=\"text/css\" rel=\"stylesheet\" href=\"css/bootstrap.css\"/>\r\n");
      out.write("\t<link href=\"http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link type=\"text/css\" rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\t<link href=\"//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<style>\r\n");
      out.write("          body { background: #FFFFFF; }\r\n");
      out.write("          .container { background: ; }\r\n");
      out.write("    </style>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<font color=\"#336699\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- tried this one on the first tut <button class=\"btn btn-success\">Test</button> -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- fixed navigaiton bar with dropdown menu\r\n");
      out.write("\t***************************************************-->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<div class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t<div class=\"navbar-inner\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"navbar-brand\">Blue Coffee</a> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav nav-pills\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider-vertical\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"resource.html\">Resources</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider-vertical\"></li>\r\n");
      out.write("\t\t\t\t\t<li  class=\"active\"><a href=\"feature.html\">Forum</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider-vertical\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"chat.html\">Chat</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider-vertical\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"about.html\">About</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Resources\r\n");
      out.write("\t**************************************************-->\r\n");
      out.write("\t<div class = \"jumbotron\">\r\n");
      out.write("\t\t<!--JSP code to get subject-->\r\n");
      out.write("\t\t<h2>Resources</h2>\r\n");
      out.write("\t\t<h5>Upload or download all the resources you need.</h5>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!--Subject Grid\r\n");
      out.write("\t*************************************************-->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t</br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
int i=0; 
      out.write("\r\n");
      out.write("\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/subjectList.jsp(79,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("matSubject");
      // /WEB-INF/jsp/subjectList.jsp(79,2) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${matSubjectList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t");
if(i==0) {
            out.write("\r\n");
            out.write("\t\t\t\t<div class=\"row\">\r\n");
            out.write("\t\t\t");
} 
            out.write("\r\n");
            out.write("\t\t\t<div class=\"col-sm-3\"><center><a href=\"subfolder?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${matSubject.subjectName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("&us=0\"><img src=\"C:\\Users\\lara312\\Documents\\GitHub\\coffee\\BCOnlineClassroom\\WebContent\\WEB-INF\\jsp\\image\\blue-folder-icon.png\"/></a></br>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${matSubject.subjectName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</br></br></center></div>\r\n");
            out.write("\t\t\t");
i++;	
			if(i==4) {
				i=0;
            out.write("\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t");
} 
            out.write("\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      }
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${matSubject.subjectDesc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Footer and Jumbotron\r\n");
      out.write("\t**************************************************\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"jumbotron\">\r\n");
      out.write("\t\t\t\t\t<h1>We are awesome</h1>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-success\">Learn more</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t-->\r\n");
      out.write("\t<!-- Accordion\r\n");
      out.write("\t**************************************************\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<h2>Accordion</h2> <hr/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"panel-group\" id=\"accordion\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a data-toggle=\"collapse\" data-parent=\"Accordion\" href=\"#section1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tSomething\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-collapse collapse in\" id=\"section1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\tThis will contain some text...\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-success\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a data-toggle=\"collapse\" data-parent=\"Accordion\" href=\"#section2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tSomething\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-collapse collapse\" id=\"section2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\tThis will contain some text... haha\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-danger\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a data-toggle=\"collapse\" data-parent=\"Accordion\" href=\"#section3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tSomething\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-collapse collapse\" id=\"section3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\tThis will contain some text... hahaha\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t-->\r\n");
      out.write("\t<!-- Tab\r\n");
      out.write("\t**************************************************\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<h2> Tab </h2> <hr/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Tabs Navigation\r\n");
      out.write("\t\t\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"> <a href=\"#tab1\" data-toggle=\"tab\"> Section 1 </a></li>\r\n");
      out.write("\t\t\t\t\t<li> <a href=\"#tab2\" data-toggle=\"tab\"> Section 2 </a></li>\r\n");
      out.write("\t\t\t\t\t<li> <a href=\"#tab3\" data-toggle=\"tab\"> Section 3 </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Tab Section \r\n");
      out.write("\t\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane active\" id=\"tab1\">\r\n");
      out.write("\t\t\t\t\t\tThis is our first tab...This is our first tab...\r\n");
      out.write("\t\t\t\t\t\tThis is our first tab...This is our first tab...\r\n");
      out.write("\t\t\t\t\t\tThis is our first tab...This is our first tab...\r\n");
      out.write("\t\t\t\t\t\tThis is our first tab...This is our first tab...\r\n");
      out.write("\t\t\t\t\t\tThis is our first tab...This is our first tab...\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane\" id=\"tab2\">\r\n");
      out.write("\t\t\t\t\t\tThis is our second tab...This is our second tab...\r\n");
      out.write("\t\t\t\t\t\tThis is our second tab...This is our second tab...\r\n");
      out.write("\t\t\t\t\t\tThis is our second tab...This is our second tab...\r\n");
      out.write("\t\t\t\t\t\tThis is our second tab...This is our second tab...\r\n");
      out.write("\t\t\t\t\t\tThis is our second tab...This is our second tab...\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane\" id=\"tab3\">\r\n");
      out.write("\t\t\t\t\t\tThis is our third tab...This is our third tab...\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Tooltips and Popovers\r\n");
      out.write("\t**************************************************\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<h2>Tooltips</h2> <hr/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-primary\" id=\"mytooltip\" href=\"#\" data-toggle=\"tooltip\" title=\"My Tooltip text\" data-placement=\"right\">\r\n");
      out.write("\t\t\t\t\tTooltip\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<h2>Popovers</h2> <hr/>\r\n");
      out.write("\t\t\t\t<button id=\"myPopOver\" class=\"btn btn-danger\" data-toggle=\"popover\" title=\"My Title\" data-content=\"This will be the body text\">\r\n");
      out.write("\t\t\t\t\tPopover\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Content Hover\r\n");
      out.write("\t**************************************************\r\n");
      out.write("\t\r\n");
      out.write("\t<hr/>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<img id=\"d1\" src=\"image/coffee.jpg\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"contenthover\">\r\n");
      out.write("\t\t\t\t\t<h3>Lorem ipsum dolor</h3>\r\n");
      out.write("\t\t\t\t\t<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. </p>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"#\" class=\"mybutton\">Lorem ipsum</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-3 col-md-offset-1\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<img id=\"d2\" src=\"image/coffee.jpg\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"contenthover\">\r\n");
      out.write("\t\t\t\t\t<h3>Lorem ipsum dolor</h3>\r\n");
      out.write("\t\t\t\t\t<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. </p>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"#\" class=\"mybutton\">Lorem ipsum</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-3 col-md-offset-1\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<img id=\"d3\" src=\"image/coffee.jpg\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"contenthover\">\r\n");
      out.write("\t\t\t\t\t<h3>Lorem ipsum dolor</h3>\r\n");
      out.write("\t\t\t\t\t<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. </p>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"#\" class=\"mybutton\">Lorem ipsum</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Footer and Modal\r\n");
      out.write("\t**************************************************-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<hr/>\r\n");
      out.write("\t\t\t\t<p>Copyright &copy; Blue Coffee.\r\n");
      out.write("\t\t\t\t<!--<a href=\"#\">Terms and Conditions</a> -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<a data-toggle=\"modal\" href=\"#myModal\">Terms and Conditions</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!--Modal -->\r\n");
      out.write("\t\t\t\t<div class=\"modal fade\" id=\"myModal\" tabinex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Terms and Conditions</h2>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>The text will go here...</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</font>\r\n");
      out.write("\t<!-- Comment --->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\t<script src=\"js/contentHover.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$('document').ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$('#mytooltip').tooltip();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#myPopOver').popover();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#d1').contenthover({\r\n");
      out.write("\t\t\t\toverlay_background:'#000',\r\n");
      out.write("\t\t\t\toverlay_opacity:0.8\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#d2').contenthover({\r\n");
      out.write("\t\t\t\teffect:'slide',\r\n");
      out.write("\t\t\t\tslide_speed:300,\r\n");
      out.write("\t\t\t\toverlay_background:'#000',\r\n");
      out.write("\t\t\t\toverlay_opacity:0.8\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#d3').contenthover({\r\n");
      out.write("\t\t\t\toverlay_width:270,\r\n");
      out.write("\t\t\t\toverlay_height:180,\r\n");
      out.write("\t\t\t\teffect:'slide',\r\n");
      out.write("\t\t\t\tslide_direction:'right',\r\n");
      out.write("\t\t\t\toverlay_x_position:'right',\r\n");
      out.write("\t\t\t\toverlay_y_position:'center',\r\n");
      out.write("\t\t\t\toverlay_background:'#000',\r\n");
      out.write("\t\t\t\toverlay_opacity:0.8\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("16 -  tutorial 1 : creating website from scratch\r\n");
      out.write("17 - tutorial 2 : responsive navigation bar\r\n");
      out.write("-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
